name: Publish dev
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  npm:
    name: npm
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Deprecate old releases
        run: npm deprecate canvacord@"~6.0.0-dev" "outdated version" || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Publish
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(git rev-parse --short HEAD).$(date +%s)
          npm publish --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}